/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/x1bJf8Aq3ie
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.375rem;
}
**/
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function CampaignTable() {
  return (
    <div className="border rounded-lg w-full">
      <div className="relative w-full overflow-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Campaign Name</TableHead>
              <TableHead>Start Date</TableHead>
              <TableHead>End Date</TableHead>
              <TableHead>Budget</TableHead>
              <TableHead>Impressions</TableHead>
              <TableHead>Clicks</TableHead>
              <TableHead>Conversions</TableHead>
              <TableHead>Conversion Rate</TableHead>
              <TableHead>ROI</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell className="font-medium">Summer Sale</TableCell>
              <TableCell>2023-06-01</TableCell>
              <TableCell>2023-08-31</TableCell>
              <TableCell>$50,000</TableCell>
              <TableCell>2,500,000</TableCell>
              <TableCell>125,000</TableCell>
              <TableCell>12,500</TableCell>
              <TableCell>10%</TableCell>
              <TableCell>2.5x</TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">Holiday Promo</TableCell>
              <TableCell>2023-11-01</TableCell>
              <TableCell>2023-12-31</TableCell>
              <TableCell>$75,000</TableCell>
              <TableCell>3,000,000</TableCell>
              <TableCell>150,000</TableCell>
              <TableCell>15,000</TableCell>
              <TableCell>10%</TableCell>
              <TableCell>3x</TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">Spring Refresh</TableCell>
              <TableCell>2023-03-15</TableCell>
              <TableCell>2023-05-31</TableCell>
              <TableCell>$40,000</TableCell>
              <TableCell>2,000,000</TableCell>
              <TableCell>100,000</TableCell>
              <TableCell>10,000</TableCell>
              <TableCell>10%</TableCell>
              <TableCell>2x</TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">Back to School</TableCell>
              <TableCell>2023-08-01</TableCell>
              <TableCell>2023-09-30</TableCell>
              <TableCell>$60,000</TableCell>
              <TableCell>2,750,000</TableCell>
              <TableCell>137,500</TableCell>
              <TableCell>13,750</TableCell>
              <TableCell>10%</TableCell>
              <TableCell>2.75x</TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">Black Friday Blitz</TableCell>
              <TableCell>2023-11-25</TableCell>
              <TableCell>2023-11-28</TableCell>
              <TableCell>$100,000</TableCell>
              <TableCell>4,000,000</TableCell>
              <TableCell>200,000</TableCell>
              <TableCell>20,000</TableCell>
              <TableCell>10%</TableCell>
              <TableCell>4x</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </div>
  )
}
